### ISSUE TITLE
Cannot start the project anymore

### ISSUE THREAD

**Issue by vvo** [CompuIves/algolia-app-search#1]
Following the README:

```sh
cd client
yarn install
yarn start
```

I endup with:

```sh
yarn start v0.24.6
$ react-scripts start 
Could not find a required file.
  Name: index.html
  Searched in: /Users/vvo/Dev/Algolia/algolia-app-search/client/public
error Command failed with exit code 1.
```

**Comment by CompuIves** [comment]
Ah thanks for sending this in!

The problem was that `public` folder was in the `.gitignore`, so the `public` folder wasn't committed. It's really strange, because until now all deployments worked.

It's fixed with this commit: https://github.com/CompuIves/algolia-app-search/commit/fddceb54a288718c3f39faa30f36d7fcc4867697.
